"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['SerialMoniter.py']
APP_NAME = 'SerialMoniter'
DATA_FILES = ['resource/icon1.jpg',
              'resource/icon2.jpg', 'resource/IMG_1776.PNG']
OPTIONS = {'argv_emulation': False,
           'strip': True,
           'plist': {
               'CFBundleName': APP_NAME,
               'CFBundleDisplayName': APP_NAME,
               'CFBundleGetInfoString': "SerialMoniter 0.1",
               'CFBundleIdentifier': "tattakaaqua.hatenablog.com",
               'CFBundleVersion': "0.1",
               'CFBundleShortVersionString': "0.1",
               'NSHumanReadableCopyright': "Copyright (C) 2017, tattaka, All Rights Reserved"
           }
           }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
